---
language: go
sudo: false
install: true

go:
- 1.x
- master

script:
- cd /home/travis/gopath/src/github.com/thomasleplus/decritic
- make dep
- make staticcheck
- make compile

notifications:
  email: true
